<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ussh.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XtermSharp\XtermSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ussh.Core.Tests" />
  </ItemGroup>
</Project>
