using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;

namespace Ussh.App.Views;

/// <summary>Shows the bundled THIRD-PARTY-NOTICES.txt (written into release builds by the packaging scripts).</summary>
public sealed class LicensesWindow : Window
{
    public LicensesWindow()
    {
        Title = "zSSH licences";
        Width = 820;
        Height = 720;
        MinWidth = 500;
        MinHeight = 300;
        WindowStartupLocation = WindowStartupLocation.CenterOwner;
        ShowInTaskbar = false;

        var close = new Button { Content = "Close", IsDefault = true, IsCancel = true, MinWidth = 90 };
        close.Click += (_, _) => Close();
        var footer = new DockPanel { Margin = new Thickness(16, 10) };
        DockPanel.SetDock(close, Dock.Right);
        footer.Children.Add(close);
        footer.Children.Add(new TextBlock
        {
            Text = "zSSH is released under the MIT License. It includes the software listed here, each under its own licence.",
            TextWrapping = TextWrapping.Wrap,
            Opacity = 0.7,
            VerticalAlignment = VerticalAlignment.Center,
        });

        var text = new SelectableTextBlock
        {
            Text = Load(),
            FontFamily = new FontFamily("Cascadia Mono, DejaVu Sans Mono, Consolas, monospace"),
            FontSize = 12,
            Margin = new Thickness(20, 16),
            TextWrapping = TextWrapping.Wrap,
        };
        var layout = new DockPanel();
        DockPanel.SetDock(footer, Dock.Bottom);
        layout.Children.Add(footer);
        layout.Children.Add(new ScrollViewer { Content = text });
        Content = layout;
    }

    /// <summary>The notices shipped next to the app, or a pointer to them in development builds.</summary>
    public static string Load()
    {
        foreach (var name in new[] { "THIRD-PARTY-NOTICES.txt", "LICENSE.txt" })
        {
            var path = Path.Combine(AppContext.BaseDirectory, name);
            if (File.Exists(path))
                return File.ReadAllText(path);
        }
        return "zSSH is released under the MIT License.\n\n" +
               "This is a development build, so the third-party notices file isn't bundled. Release builds include " +
               "THIRD-PARTY-NOTICES.txt, generated by tools/generate-third-party-notices.py, listing every bundled " +
               "component with its licence.";
    }
}
